#!/usr/bin/with-contenv bash

# s6-echo "1"

exec s6-setuidgid abc java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap \
	-Djava.net.preferIPv4Stack=true -Djava.awt.headless=true \
	-Dorg.restlet.engine.loggerFacadeClass=org.restlet.ext.slf4j.Slf4jLoggerFacade \
	-Dderby.system.home=/config/serviio/library \
	-Dserviio.home=/app/serviio -Dplugins.location=/config/serviio \
	-Dserviio.defaultTranscodeFolder=/transcode -Dffmpeg.location=/usr/bin/ffmpeg \
        $SERVIIO_OPTS org.serviio.MediaServer
